name: weekly_ui
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.0
  circle_list: ^1.0.4
  circle_wheel_scroll: ^0.0.1+1
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  font_awesome_flutter: ^8.11.0
  google_fonts: ^1.1.1
  random_user: ^0.3.0
  flutter_tindercard: ^0.2.0
  sizer: ^1.1.8
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/job_search.svg
    - assets/people.svg
